---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  
  - name: tools
    image: rsmaxwell/tools:latest
    command:
    - cat
    tty: true

  - name: gcc
    image: gcc:latest
    command:
    - cat
    tty: true

  - name: golang
    image: golang:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /go/pkg
      name: golang-vol

  - name: maven
    image: maven:3.8.6-eclipse-temurin-17
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/.m2/repository
      name: maven-vol
    - mountPath: /root/.m2
      name: maven-settings
      readOnly: true



  - name: gradle
    image: rsmaxwell/gradle:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /home/gradle
      name: gradle-vol



  volumes:
  - name: maven-vol
    persistentVolumeClaim:
      claimName: maven-pvc
  - name: maven-settings
    secret:
      secretName: maven-settings
      optional: false
  - name: golang-vol
    persistentVolumeClaim:
      claimName: golang-pvc
  - name: gradle-vol
    persistentVolumeClaim:
      claimName: gradle-pvc
